# base image
FROM node:alpine

ARG AUTH_SERVER_ENDPOINT
ARG AUTH_SERVER_CLIENT_ID
ARG AUTH_SERVER_CLIENT_SECRET
ARG AUTH_SERVER_REDIRECT_URI

ENV REACT_APP_AUTH_SERVER_ENDPOINT $AUTH_SERVER_ENDPOINT
ENV REACT_APP AUTH_SERVER_CLIENT_ID $AUTH_SERVER_CLIENT_ID
ENV REACT_APP_AUTH_SERVER_CLIENT_SECRET $AUTH_SERVER_CLIENT_SECRET
ENV REACT_APP_AUTH_SERVER_REDIRECT_URI $AUTH_SERVER_REDIRECT_URI

# create & set working directory
RUN mkdir -p /usr/src
WORKDIR /usr/src

# copy source files
COPY . /usr/src

# install dependencies
RUN npm install

EXPOSE 3000

CMD ["npm", "start"]
